GET http://localhost:6000/api/todos

###
GET http://localhost:6000/api/todos/0a203c81-34dd-4143-9bb3-870b7b273644

###
POST http://localhost:6000/api/todos
Content-Type: application/json

{
    "title": "First Todo",
    "description": "The description of the first todo",
    "completed": false 
}

###
PUT http://localhost:6000/api/todos/1
Content-Type: application/json

{
    "id": 22,
    "name": "mantle"
}

###
DELETE http://localhost:6000/api/todos/12