GET http://localhost:6000/api/todos

###
GET http://localhost:6000/api/todos/4

###
POST http://localhost:6000/api/todos
Content-Type: application/json

{
    "name": "naming"
}

###
PUT http://localhost:6000/api/todos/1
Content-Type: application/json

{
    "id": 22,
    "name": "mantle"
}

###
DELETE http://localhost:6000/api/todos/12